# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxc6htXde2FlRGVyZ-IT_FrcxvV7Sri2
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# LOADING DATA INTO DATAFRAME
data = pd.read_csv("student-mat.csv", sep=";")
print("Data loaded successfully")

# DATA EXPLORATION
print(data.head())
print("\nDataset info:")
print(data.info())

# DATA CLEANING
print("\nMissing values:")
print(data.isnull().sum())

# Remove duplicates
data = data.drop_duplicates()

# DATA ANALYSIS

# Avg score in math (G3)
avg_score = data['G3'].mean()
print(f"\nAverage math score (G3): {avg_score:.2f}")

# Number of students scored >15
students_abv_15 = len(data[data['G3'] > 15])
print(f"No. of students scored >15: {students_abv_15}")

# Correlation between study time and final grade
correlation = data['studytime'].corr(data['G3'])
print(f"Correlation b/w studytime and final grade: {correlation:.2f}")

# Gender with higher avg final grade
avg_grade_by_gender = data.groupby('sex')['G3'].mean()
print("\nAverage final grade by gender:")
print(avg_grade_by_gender)

#DATA VISUALIZATION

#Histogram of final grades

plt.figure(figsize=(8,5))

plt.hist(data['G3'], bins=10, color='blue', edgecolor='black')

plt.title("final grades distribution")

plt.xlabel("Final grade")

plt.ylabel("Frequency")

plt.show()

#Scatter plot of study time vs final grade

plt.figure(figsize=(8,5))

sns.scatterplot(data=data, x='studytime', y='G3', hue='sex')

plt.xlabel("Studytime(hrs)")

plt.ylabel("Final grade")

plt.legend(title="Gender")

plt.show()

#Barchart of avg scores by gender

plt.figure(figsize=(8,5))

avg_grade_by_gender.plot(kind='bar', color=['blue', 'pink'])

plt.title("Avg Final grade by gender")

plt.xlabel("Gender")

plt.ylabel("Avg final grade")

plt.xticks (rotation=0)

plt.show()